import os
from pathlib import Path
from typing import Optional

import typer
from pydantic import ValidationError
from pydantic_settings import BaseSettings, SettingsConfigDict
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt

console = Console()


class Config(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=os.getenv("TRACKIFY_ENV_FILE", ".env"),
        env_file_encoding="utf-8",
        case_sensitive=True,
        extra="ignore",
    )

    GITHUB_ACCESS_TOKEN: str
    REPO_NAME: str
    WAKATIME_API_KEY: str
    CLOCKIFY_API_KEY: str
    CLOCKIFY_PROJECT_ID: str
    CLOCKIFY_WORKSPACE_ID: str


# Configuration field metadata for interactive prompts
CONFIG_FIELDS = {
    "GITHUB_ACCESS_TOKEN": {
        "prompt": "GitHub Personal Access Token",
        "help": "Get it from: https://github.com/settings/tokens (needs 'repo' scope)",
        "password": True,
    },
    "REPO_NAME": {
        "prompt": "GitHub Repository Name",
        "help": "Format: owner/repo (e.g., 'pedroifgonzalez/trackify')",
        "password": False,
    },
    "WAKATIME_API_KEY": {
        "prompt": "WakaTime API Key",
        "help": "Find it at: https://wakatime.com/settings/account",
        "password": True,
    },
    "CLOCKIFY_API_KEY": {
        "prompt": "Clockify API Key",
        "help": "Generate at: https://app.clockify.me/user/settings",
        "password": True,
    },
    "CLOCKIFY_PROJECT_ID": {
        "prompt": "Clockify Project ID",
        "help": "Find in Clockify URL when viewing your project",
        "password": False,
    },
    "CLOCKIFY_WORKSPACE_ID": {
        "prompt": "Clockify Workspace ID",
        "help": "Find in Clockify URL when viewing your workspace",
        "password": False,
    },
}


def interactive_setup(env_file: Path = Path(".env")) -> None:
    """Interactively prompt user for configuration values and save to .env file."""
    console.print(
        Panel.fit(
            "[bold cyan]Trackify Configuration Setup[/bold cyan]\n\n"
            "Let's set up your configuration. You'll need API keys from:\n"
            "• GitHub (https://github.com/settings/tokens)\n"
            "• WakaTime (https://wakatime.com/settings/account)\n"
            "• Clockify (https://app.clockify.me/user/settings)",
            border_style="cyan",
        )
    )
    console.print()

    config_values = {}

    for field_name, field_info in CONFIG_FIELDS.items():
        console.print(f"[bold]{field_info['prompt']}[/bold]")
        console.print(f"[dim]{field_info['help']}[/dim]")

        value = Prompt.ask(
            f"Enter {field_info['prompt']}",
            password=field_info["password"],
        )
        config_values[field_name] = value
        console.print()

    # Write to .env file
    with open(env_file, "w") as f:
        f.write("# Trackify Configuration\n")
        f.write("# Generated by trackify setup\n\n")
        for key, value in config_values.items():
            f.write(f"{key}={value}\n")

    console.print(
        f"[bold green]✓[/bold green] Configuration saved to {env_file}",
        style="bold",
    )
    console.print(
        "[dim]You can edit this file manually or run 'trackify setup' again to reconfigure.[/dim]"
    )


def get_config(interactive: bool = False) -> Config:
    """Get configuration, optionally prompting for missing values.

    Args:
        interactive: If True, prompt user for missing values instead of raising error

    Returns:
        Config: Loaded configuration

    Raises:
        ValidationError: If config is invalid and interactive=False
    """
    try:
        return Config()
    except ValidationError as e:
        if not interactive:
            # Extract missing fields from validation error
            missing_fields = []
            for error in e.errors():
                if error["type"] == "missing":
                    field_name = error["loc"][0]
                    missing_fields.append(field_name)

            console.print(
                "[bold red]Configuration Error:[/bold red] Missing required environment variables",
                style="bold",
            )
            console.print()

            for field in missing_fields:
                field_info = CONFIG_FIELDS.get(field, {})
                console.print(f"  • [yellow]{field}[/yellow]")
                if "help" in field_info:
                    console.print(f"    [dim]{field_info['help']}[/dim]")

            console.print()
            console.print(
                "[bold]Run [cyan]trackify setup[/cyan] to configure interactively,[/bold]"
            )
            console.print(
                "[bold]or create a .env file with the required variables.[/bold]"
            )
            console.print()
            console.print("[dim]See .env.example for reference[/dim]")

            raise typer.Exit(code=1)
        else:
            # Interactive mode - prompt for values
            console.print(
                "[yellow]⚠[/yellow] Configuration incomplete. Let's set it up now.",
                style="bold",
            )
            console.print()
            interactive_setup()
            # Try loading again
            return Config()


# Global config instance - will be initialized lazily
_config: Optional[Config] = None


def get_or_prompt_config() -> Config:
    """Get config, prompting user if it fails to load."""
    global _config
    if _config is None:
        _config = get_config(interactive=True)
    return _config


# For backward compatibility, try to load config at module level
# but don't fail if it's missing (let commands handle it)
try:
    config = Config()
except ValidationError:
    # Config will be loaded on-demand by commands
    config = None  # type: ignore
